spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Load DB config from classpath properties (private.properties)
spring.config.import=optional:classpath:/private.properties




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true







